TEMPLATE = subdirs
SUBDIRS += \
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/UserTaskManagerView/UserTaskManagerView.pro \ #https://gitlab.com/c4rb0n_un1t/UserTaskManagerView.git
#/home/keereel/Projects/MASS/MASS-Plugins/Plugins/LogicPlugin/LogicPlugin.pro \ #https://gitlab.com/c4rb0n_un1t/LogicPlugin.git
#/home/keereel/Projects/MASS/MASS-Plugins/Plugins/MusicPlayerView/MusicPlayerView.pro \ #https://gitlab.com/c4rb0n_un1t/MusicPlayerView.git
#/home/keereel/Projects/MASS/MASS-Plugins/Plugins/MusicPlayerTrackDataExtention/MusicPlayerTrackDataExtention.pro \ #https://gitlab.com/c4rb0n_un1t/MusicPlayerTrackDataExtention.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/PluginLinkerCommand/PluginLinkerCommand.pro \ #https://gitlab.com/c4rb0n_un1t/PluginLinkerCommand.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/AsyncDataBase/AsyncDataBase.pro \ #git@gitlab.com:c4rb0n_un1t/AsyncDataBase.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/TaskSketchManager/TaskSketchManager.pro \ #https://gitlab.com/c4rb0n_un1t/TaskSketchManager.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/UserTaskDateDataExtention/UserTaskDateDataExtention.pro \ #https://gitlab.com/c4rb0n_un1t/UserTaskDateDataExtention.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/UserTaskPomodoroDataExtention/UserTaskPomodoroDataExtention.pro \ #https://gitlab.com/c4rb0n_un1t/UserTaskPomodoroDataExtention.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/ProjectManager/ProjectManager.pro \ #https://gitlab.com/c4rb0n_un1t/ProjectManager.git
#/home/keereel/Projects/MASS/MASS-Plugins/Plugins/CLIManager/CLIManager.pro \ #https://gitlab.com/c4rb0n_un1t/CLIManager.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/UserTaskProjectDataExtention/UserTaskProjectDataExtention.pro \ #https://gitlab.com/c4rb0n_un1t/UserTaskProjectDataExtention.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/ExtendableDataManager/ExtendableDataManager.pro \ #https://gitlab.com/c4rb0n_un1t/ExtendableDataManager.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/HabitsTracker/HabitsTracker.pro \ #https://gitlab.com/c4rb0n_un1t/HabitsTracker.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/HabitsTrackerView/HabitsTrackerView.pro \ #https://gitlab.com/c4rb0n_un1t/HabitsTrackerView.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/PluginLinker/PluginLinker.pro \ #https://gitlab.com/c4rb0n_un1t/PluginLinker.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/PomodoroManagerView/PomodoroManagerView.pro \ #https://gitlab.com/c4rb0n_un1t/PomodoroManagerView.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/NotificationManager/NotificationManager.pro \ #https://gitlab.com/c4rb0n_un1t/NotificationManager.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/DevProjectManagerDataExtention/DevProjectManagerDataExtention.pro \ #https://gitlab.com/c4rb0n_un1t/MusicPlayerTrackDataExtention.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/DataBase/DataBase.pro \ #https://gitlab.com/c4rb0n_un1t/DataBase.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/GUIManager/GUIManager.pro \ #https://gitlab.com/c4rb0n_un1t/GUIManager.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/DevPluginInfoDataExtention/DevPluginInfoDataExtention.pro \ #https://gitlab.com/c4rb0n_un1t/MusicPlayerTrackDataExtention.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/TaskSketchManagerView/TaskSketchManagerView.pro \ #https://gitlab.com/c4rb0n_un1t/TaskSketchManagerView.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/ToDoListCommand/ToDoListCommand.pro \ #https://gitlab.com/c4rb0n_un1t/ToDoListCommand.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/UserTasksCalendarView/UserTasksCalendarView.pro \ #https://gitlab.com/c4rb0n_un1t/UserTasksCalendarView.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/UserTaskNotes/UserTaskNotes.pro \ #https://gitlab.com/c4rb0n_un1t/UserTaskNotes.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/ProjectManagerView/ProjectManagerView.pro \ #https://gitlab.com/c4rb0n_un1t/ProjectManagerView.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/UserTaskDataExtention/UserTaskDataExtention.pro \ #https://gitlab.com/c4rb0n_un1t/UserTaskDataExtention.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/UserTaskNotesView/UserTaskNotesView.pro \ #https://gitlab.com/c4rb0n_un1t/UserTaskNotesView.git
#/home/keereel/Projects/MASS/MASS-Plugins/Plugins/MusicPlayer/MusicPlayer.pro \ #https://gitlab.com/c4rb0n_un1t/MusicPlayer.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/ToDoListView/ToDoListView.pro \ #https://gitlab.com/c4rb0n_un1t/ToDoListView.git
#/home/keereel/Projects/MASS/MASS-Plugins/Plugins/ViewPlugin/ViewPlugin.pro \ #https://gitlab.com/c4rb0n_un1t/ViewPlugin.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/PomodoroManager/PomodoroManager.pro \ #https://gitlab.com/c4rb0n_un1t/PomodoroManager.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/Core/Core.pro \ #https://gitlab.com/c4rb0n_un1t/Core.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/UserTasksCalendar/UserTasksCalendar.pro \ #git@gitlab.com:c4rb0n_un1t/UserTasksCalendar.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/PomodoroSettingsDataExtention/PomodoroSettingsDataExtention.pro \ #https://gitlab.com/c4rb0n_un1t/PomodoroSettingsDataExtention.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/HabitsTrackerDataExtention/HabitsTrackerDataExtention.pro \ #https://gitlab.com/c4rb0n_un1t/HabitsTrackerDataExtention.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/GridMainMenuView/GridMainMenuView.pro \ #https://gitlab.com/c4rb0n_un1t/GridMainMenuView.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/PluginLinkerView/PluginLinkerView.pro \ #https://gitlab.com/c4rb0n_un1t/PluginLinkerView.git
/home/keereel/Projects/MASS/MASS-Plugins/Plugins/UserTaskRepeatDataExtention/UserTaskRepeatDataExtention.pro \ #https://gitlab.com/c4rb0n_un1t/UserTaskRepeatDataExtention.git
#/home/keereel/Projects/MASS/MASS-Plugins/Plugins/MusicPlayerTrackProgressDataExtention/MusicPlayerTrackProgressDataExtention.pro \ #https://gitlab.com/c4rb0n_un1t/MusicPlayerTrackProgressDataExtention.git
